{
 "title": "LiveKit Server",
 "tags": [ "livekit" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "LiveKit Packet Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(livekit_packet_bytes{direction=\"outgoing\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(livekit_packet_bytes{direction=\"incoming\"}[$__rate_interval]))",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(livekit_room_total)", "legendFormat": "rooms" }
   ]
  },
  {
   "title": "Participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(livekit_participant_total)", "legendFormat": "participants" }
   ]
  },
  {
   "title": "Published Audio Tracks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(livekit_track_published_total{kind=\"AUDIO\"})",
     "legendFormat": "audio tracks"
    }
   ]
  },
  {
   "title": "Participants Joined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(livekit_node_service_operation{status=\"success\",type=\"participant_join\"}[$__rate_interval])) * $__rate_interval",
     "legendFormat": "joined"
    }
   ]
  },
  {
   "title": "Service Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(livekit_node_service_operation{status!=\"success\"}[$__rate_interval])) by (type, status) * $__rate_interval",
     "legendFormat": "({{status}}) {{type}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1m" },
    { "expr": "node_load5", "legendFormat": "5m" },
    { "expr": "node_load15", "legendFormat": "15m" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "used"
    }
   ]
  }
 ]
}